name: Receive Release Dispatch

on:
  repository_dispatch:
    types: [test-release]
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{ github.event.client_payload.github.ref }}
#       - name: Get the version
#         id: get_version
#         run: echo ::set-output name=VERSION::${${{ github.event.client_payload.ref }}/refs\/tags\//}
#       - run: echo $VERSION
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=RELEASE_TAG::${${{ github.event.client_payload.github.ref }}//refs\/tags\/}
          echo ::set-output name=RELEASE_TYPE::${{ github.event.client_payload.github.event.action }}
      - name: Build base image
        run: |
          echo $RELEASE_TAG
          echo $RELEASE_TYPE       
        env:
          RELEASE_TAG: ${{ steps.branch_name.outputs.RELEASE_TAG }}
          RELEASE_TYPE: ${{ steps.branch_name.outputs.RELEASE_TYPE }}
