name: Receive Release Dispatch

on:
  repository_dispatch:
    types: [test-release]
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{ github.event.client_payload.ref }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${github.event.client_payload.ref#refs/tags/}
      - run: echo $VERSION
