name: Receive Payload

on:
  repository_dispatch:
    types: [test-release]
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Read Payload
        id: branch_name
        run: |
          echo ::set-output name=RELEASE_TAG::${{ github.event.client_payload.github.event.release.tag_name }}
          echo ::set-output name=RELEASE_NAME::${{ github.event.client_payload.github.event.release.name }}
          if [ ${{ github.event.client_payload.github.event.release.prerelease }} ]
          then
            echo "Prerelease"
            release=Pre-release
          else
            echo "Stable"
            release=Stable
          fi
          echo ::set-output name=RELEASE_TYPE::${release}
      - name: Create Variables
        run: |
          echo $RELEASE_TAG
          echo $RELEASE_NAME
          echo $RELEASE_TYPE       
        env:
          RELEASE_TAG: ${{ steps.branch_name.outputs.RELEASE_TAG }}
          RELEASE_NAME: ${{ steps.branch_name.outputs.RELEASE_NAME }}
          RELEASE_TYPE: ${{ steps.branch_name.outputs.RELEASE_TYPE }}
